# https://github.com/lihaoyi/mill/blob/master/.travis.yml
language: scala
sudo: required
dist: trusty

matrix:
  include:
  - stage: build
    env: CI_SCRIPT="mill _.test"
    jdk: oraclejdk8
#  - stage: release
#    env: CI_SCRIPT="ci/on-master.py ci/publish-docs.sh"
#    jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.1.6/0.1.6 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier
